In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style('whitegrid')

In [58]:
df =pd.read_csv("https://www.football-data.co.uk/new/BRA.csv")

In [59]:
df.head()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,...,5.31,1.69,3.50,4.90,NaN,NaN,NaN,NaN,NaN,NaN
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,...,2.70,2.59,3.23,2.58,NaN,NaN,NaN,NaN,NaN,NaN
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,...,7.22,1.59,3.67,5.64,NaN,NaN,NaN,NaN,NaN,NaN
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,...,3.15,2.35,3.26,2.84,NaN,NaN,NaN,NaN,NaN,NaN
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,...,4.41,1.89,3.33,3.89,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df.columns

Index(['Country', 'League', 'Season', 'Date', 'Time', 'Home', 'Away', 'HG',
       'AG', 'Res', 'PSCH', 'PSCD', 'PSCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH',
       'AvgCD', 'AvgCA', 'BFECH', 'BFECD', 'BFECA', 'B365CH', 'B365CD',
       'B365CA'],
      dtype='str')

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5525 entries, 0 to 5524
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  5525 non-null   str
 1   League   5525 non-null   str
 2   Season   5525 non-null   int64
 3   Date     5525 non-null   str
 4   Time     5525 non-null   str
 5   Home     5525 non-null   str
 6   Away     5525 non-null   str
 7   HG       5524 non-null   float64
 8   AG       5524 non-null   float64
 9   Res      5524 non-null   str
 10  PSCH     5275 non-null   float64
 11  PSCD     5275 non-null   float64
 12  PSCA     5275 non-null   float64
 13  MaxCH    5525 non-null   float64
 14  MaxCD    5525 non-null   float64
 15  MaxCA    5525 non-null   float64
 16  AvgCH    5525 non-null   float64
 17  AvgCD    5525 non-null   float64
 18  AvgCA    5525 non-null   float64
 19  BFECH    790 non-null    float64
 20  BFECD    790 non-null    float64
 21  BFECA    790 non-null    float64
 22  B365CH   407 non-null    float64
 23  B365CD   407 non-null    float64
 24  B365CA   407 non-null    float64
dtypes: float64(17), int64(1), str(7)
memory usage: 1.1 MB

In [62]:
df.isna().sum()

Country       0
League        0
Season        0
Date          0
Time          0
Home          0
Away          0
HG            1
AG            1
Res           1
PSCH        250
PSCD        250
PSCA        250
MaxCH         0
MaxCD         0
MaxCA         0
AvgCH         0
AvgCD         0
AvgCA         0
BFECH      4735
BFECD      4735
BFECA      4735
B365CH     5118
B365CD     5118
B365CA     5118
dtype: int64

In [63]:
df.shape

(5525, 25)

In [64]:
df = df.loc[:, ['Date','Season','Home', 'Away', 'HG','AG', 'Res', 'PSCH', 'PSCD', 'PSCA']]

In [65]:
df = df.dropna()

In [66]:
df.isna().sum()

Date      0
Season    0
Home      0
Away      0
HG        0
AG        0
Res       0
PSCH      0
PSCD      0
PSCA      0
dtype: int64

In [67]:
df.groupby("Home").agg(
    media_odd = ('PSCH','mean')
).reset_index()

              Home  media_odd
0       America MG   2.913263
1     Athletico-PR   2.210482
2      Atletico GO   2.916316
3      Atletico-MG   1.788106
4             Avai   3.292105
5            Bahia   2.355990
6      Botafogo RJ   2.434115
7       Bragantino   2.178125
8              CSA   4.408421
9            Ceara   2.508108
10  Chapecoense-SC   2.893788
11     Corinthians   2.100304
12        Coritiba   2.567778
13        Criciuma   2.747895
14        Cruzeiro   1.915749
15          Cuiaba   2.855789
16     Figueirense   2.765921
17     Flamengo RJ   1.760795
18      Fluminense   2.211597
19       Fortaleza   2.334697
20           Goias   3.000150
21          Gremio   1.919429
22   Internacional   1.913918
23       Joinville   3.168947
24       Juventude   3.367297
25        Mirassol   2.372941
26         Nautico   2.836316
27       Palmeiras   1.755510
28          Parana   4.492632
29     Ponte Preta   2.419579
30      Portuguesa   2.575000
31      Santa Cruz   2.533684
32          Santos   2.166107
33       Sao Paulo   1.919659
34    Sport Recife   2.656071
35           Vasco   2.624362
36         Vitoria   2.534046

In [68]:
df_raw = df.copy()

## Analise das variaveis

In [69]:

class_counts = df_raw['Res'].value_counts()
print('Proporção', class_counts / len(df_raw))

Proporção Res
H    0.485498
D    0.268246
A    0.246256
Name: count, dtype: float64

In [70]:
df_raw[['PSCH', 'PSCD', 'PSCA']].describe()

              PSCH         PSCD         PSCA
count  5275.000000  5275.000000  5275.000000
mean      2.309354     3.635761     4.677033
std       0.949609     0.655082     2.467124
min       1.080000     2.540000     1.150000
25%       1.700000     3.240000     2.990000
50%       2.080000     3.440000     4.030000
75%       2.620000     3.830000     5.700000
max      17.680000    12.250000    29.580000

# Engenharia de features

In [71]:
df_raw['Date_parsed'] =pd.to_datetime(df_raw['Date'], format= '%d/%m/%Y')
df_raw = df_raw.sort_values('Date_parsed').reset_index(drop=True)

In [72]:
# covenverter odds em Probabilidade 
df_raw['p_home'] = 1/df_raw['PSCH']
df_raw['p_draw'] = 1/df_raw['PSCD']
df_raw['p_away'] = 1/df_raw['PSCA']

In [73]:
# remover o juice da casa de aposta
total = ( 
    df_raw['p_home'] +
    df_raw['p_draw'] +
    df_raw['p_away']
)

In [74]:
df_raw["p_home"] /= total
df_raw["p_away"] /= total
df_raw["p_draw"] /= total

In [75]:
# diferença porbabilidade casa e fora 
df_raw['dif_prob'] = df_raw['p_home'] - df_raw['p_away']

In [76]:
df_raw['dif_draw'] = df_raw['p_home'] - df_raw['p_draw']

In [77]:
df_raw['goal_diff'] = df_raw['HG'] - df_raw['AG']

In [78]:
df_raw['goal_total'] = df_raw['HG'] + df_raw['AG']

# Categorizar as probabilidades do times

In [79]:
labels = [
    "Grande Zebra",
    "Zebra",
    "Leve Zebra",
    "Equilibrado",
    "Leve Favorito",
    "Favorito",
    "Super Favorito"
]

In [80]:
df_raw["bucket_favoritismo"] = pd.qcut(
    df_raw["dif_prob"],
    q=7,
    labels=labels,
    duplicates="drop"
)

In [81]:
df_raw.tail()

,Date,Season,Home,Away,HG,AG,Res,PSCH,PSCD,PSCA,Date_parsed,p_home,p_draw,p_away,dif_prob,dif_draw,goal_diff,goal_total,bucket_favoritismo
5270,07/12/2025,2025,Ceara,Palmeiras,1.0,3.0,A,1.99,3.31,3.98,2025-12-07,0.475917,0.286125,0.237958,0.237958,0.189792,-2.0,4.0,Equilibrado
5271,07/12/2025,2025,Botafogo RJ,Fortaleza,4.0,2.0,H,1.70,4.00,4.58,2025-12-07,0.556737,0.236613,0.206649,0.350088,0.320124,2.0,6.0,Leve Favorito
5272,07/12/2025,2025,Atletico-MG,Vasco,5.0,0.0,H,1.51,4.11,6.65,2025-12-07,0.627170,0.230420,0.142410,0.484760,0.396750,5.0,5.0,Super Favorito
5273,07/12/2025,2025,Corinthians,Juventude,1.0,1.0,D,1.76,3.39,5.12,2025-12-07,0.536791,0.278688,0.184522,0.352269,0.258103,0.0,2.0,Leve Favorito
5274,07/12/2025,2025,Vitoria,Sao Paulo,1.0,0.0,H,2.47,3.08,3.10,2025-12-07,0.384804,0.308593,0.306602,0.078202,0.076211,1.0,1.0,Leve Zebra

# Média de gols dos ultimos 5 jogos

In [82]:
# média de gols nos ultimos 5 jogos 

df_raw['home_last5_goals'] =(
    df_raw.groupby('Home')['HG']
    .transform(lambda s: s.shift().rolling(window=5, min_periods=1).mean())
    
)

df_raw['away_last5_goals'] =(
    df_raw.groupby('Away')['AG']
    .transform(lambda s: s.shift().rolling(window=5, min_periods=1).mean())
)

In [83]:
# força da defesa 
df_raw['home_last5_concede'] = df_raw.groupby('Home')['AG'].transform(
    lambda s: s.shift().rolling(5, min_periods=1).mean()
)

df_raw['away_last5_concede'] = df_raw.groupby('Away')['HG'].transform(
    lambda s: s.shift().rolling(5, min_periods=1).mean()
)

# Média exponencial do gols EWMA

In [84]:
df_raw['home_ewma_5_goals'] = (
    df_raw.groupby('Home')['HG']
    .transform(lambda s : s.shift().ewm(span = 10, adjust = False).mean())
)

df_raw['away_ewma_5_goals'] = (
    df_raw.groupby('Away')['AG']
    .transform(lambda s : s.shift().ewm(span = 10, adjust = False).mean())
)

# Winrate dos ultimos 5 jogos

In [85]:
res_map ={ 'H' :2, 'D': 1, 'A' : 0}
df_raw['Res_num'] = df_raw['Res'].map(res_map)

In [86]:
df_raw['home_last5_winrate'] =(
    df_raw.groupby('Home')['Res_num']
    .transform(lambda s: s.shift().rolling(5, min_periods= 1).apply(lambda x : (x==2).mean()))
)

df_raw['away_last5_winrate'] =(
    df_raw.groupby('Away')['Res_num']
    .transform(lambda s: s.shift().rolling(5, min_periods= 1).apply(lambda x : (x==0).mean()))
)

In [87]:
df_raw["home_points"] = np.select(
    [
        df_raw["Res_num"] == 2,
        df_raw["Res_num"] == 1,
        df_raw["Res_num"] == 0
    ],
    [
        3,
        1,
        0
    ]
)

df_raw["away_points"] = np.select(
    [
        df_raw["Res_num"] == 0,
        df_raw["Res_num"] == 1,
        df_raw["Res_num"] == 2
    ],
    [
        3,
        1,
        0
    ]
)

# PONTOS NAS ULTIMAS 5 PARTIDAS PPG

In [88]:
df_raw["home_last5_ppg"] = (
    df_raw
    .groupby("Home")["home_points"]
    .transform(
        lambda s: s.shift().rolling(5, min_periods=1).mean()
    )
)


df_raw["away_last5_ppg"] = (
    df_raw
    .groupby("Away")["away_points"]
    .transform(
        lambda s: s.shift().rolling(5, min_periods=1).mean()
    )
)

# CALCULANDO O CAOS "ENTROPIA"

In [89]:
H_MAX = np.log2(3)

def calc_entropy(row, normalize=True):

    p = np.array([
        row["p_home"],
        row["p_draw"],
        row["p_away"]
    ])

    p = p[p > 0]

    h = -(p * np.log2(p)).sum()

    if normalize:
        h /= H_MAX

    return h

df_raw["entropy"] = df_raw.apply(calc_entropy, axis=1)

| Entropia | Interpretação                   |
| -------: | ------------------------------- |
|     0.00 | Resultado praticamente definido |
|     0.20 | Super favorito                  |
|     0.40 | Favorito                        |
|     0.60 | Leve favorito                   |
|     0.80 | Jogo equilibrado                |
|     1.00 | Máxima incerteza                |

In [90]:
# SELECIONAR UMA AMOSTRA ALEATÓRIA
df_raw.sample(10)

,Date,Season,Home,Away,HG,AG,Res,PSCH,PSCD,PSCA,...,home_ewma_5_goals,away_ewma_5_goals,Res_num,home_last5_winrate,away_last5_winrate,home_points,away_points,home_last5_ppg,away_last5_ppg,entropy
74,08/07/2012,2012,Fluminense,Flamengo RJ,1.0,0.0,H,2.04,3.67,3.85,...,2.066116,0.966942,2,0.25,0.0,3,0,1.666667,0.666667,0.958456
2689,11/05/2019,2019,Fluminense,Botafogo RJ,0.0,1.0,A,2.10,3.30,3.95,...,0.593337,0.627667,0,0.20,0.2,0,3,1.000000,0.800000,0.966132
4618,02/06/2024,2024,Vasco,Flamengo RJ,1.0,6.0,A,5.12,3.89,1.71,...,1.503413,1.258992,0,0.60,0.4,0,3,1.800000,1.600000,0.894971
1645,03/07/2016,2016,Botafogo RJ,Santa Cruz,2.0,1.0,H,1.56,4.05,7.21,...,0.931836,1.326412,2,0.40,0.0,3,0,1.600000,0.400000,0.825796
3748,20/11/2021,2021,Chapecoense-SC,Gremio,1.0,3.0,A,6.13,4.31,1.56,...,0.931574,0.613419,0,0.00,0.0,0,3,0.600000,0.000000,0.840364
4159,09/11/2022,2022,Fortaleza,Bragantino,6.0,0.0,H,1.82,3.78,4.64,...,1.417085,1.087155,2,0.60,0.2,3,0,2.200000,0.800000,0.920848
674,20/10/2013,2013,Botafogo RJ,Vasco,2.0,2.0,D,2.35,3.52,3.17,...,1.238186,1.300009,1,0.40,0.0,1,1,1.200000,0.400000,0.986039
4326,18/07/2023,2023,Goias,Atletico-MG,0.0,0.0,D,4.27,3.46,1.98,...,1.099593,1.224312,1,0.20,0.6,1,1,0.800000,2.000000,0.949276
2246,16/11/2017,2017,Palmeiras,Sport Recife,5.0,1.0,H,1.57,4.47,6.09,...,1.680890,0.769594,2,0.40,0.2,3,0,1.600000,0.800000,0.838529
4794,01/09/2024,2024,Athletico-PR,Palmeiras,0.0,2.0,A,3.81,3.58,2.03,...,1.134553,1.056919,0,0.00,0.0,0,3,0.200000,0.600000,0.960135

In [91]:
df_raw[df_raw['entropy'] <= 0.6]

,Date,Season,Home,Away,HG,AG,Res,PSCH,PSCD,PSCA,...,home_ewma_5_goals,away_ewma_5_goals,Res_num,home_last5_winrate,away_last5_winrate,home_points,away_points,home_last5_ppg,away_last5_ppg,entropy
691,02/11/2013,2013,Atletico-MG,Nautico,5.0,0.0,H,1.24,6.54,15.15,...,1.750288,0.636468,2,0.8,0.2,3,0,2.6,0.8,0.590968
739,24/11/2013,2013,Athletico-PR,Nautico,6.0,1.0,H,1.24,6.61,15.44,...,1.734918,0.426065,2,1.0,0.2,3,0,3.0,0.6,0.586835
745,01/12/2013,2013,Vasco,Nautico,2.0,0.0,H,1.20,7.59,16.87,...,1.471874,0.530417,2,0.6,0.0,3,0,2.0,0.0,0.543036
752,08/12/2013,2013,Internacional,Ponte Preta,0.0,0.0,D,1.23,6.41,17.21,...,1.512327,0.915716,1,0.4,0.0,1,1,1.6,0.6,0.576889
870,26/07/2014,2014,Cruzeiro,Figueirense,5.0,0.0,H,1.24,6.30,16.80,...,2.432479,0.804434,2,0.8,0.4,3,0,2.6,1.4,0.585008
1130,06/12/2014,2014,Corinthians,Criciuma,2.0,1.0,H,1.24,6.25,16.65,...,1.663472,0.811205,2,0.8,0.0,3,0,2.6,0.2,0.587427
1229,28/06/2015,2015,Atletico-MG,Joinville,1.0,0.0,H,1.23,6.52,16.59,...,2.098920,0.181818,2,0.4,0.0,3,0,1.4,0.0,0.578225
1370,09/09/2015,2015,Atletico-MG,Avai,2.0,0.0,H,1.24,6.57,14.50,...,1.386283,0.519883,2,0.6,0.0,3,0,1.8,0.2,0.595623
1892,11/12/2016,2016,Sport Recife,Figueirense,2.0,0.0,H,1.24,6.36,15.86,...,1.156262,0.275714,2,0.6,0.0,3,0,2.0,0.2,0.590180
1893,11/12/2016,2016,Santos,America MG,1.0,0.0,H,1.21,7.39,16.20,...,1.929552,0.347052,2,0.8,0.0,3,0,2.6,0.0,0.554838
1985,22/06/2017,2017,Palmeiras,Atletico GO,1.0,0.0,H,1.25,6.21,15.60,...,1.743690,0.703885,2,0.8,0.2,3,0,2.6,0.8,0.598581
2014,09/07/2017,2017,Gremio,Avai,0.0,2.0,A,1.21,6.99,18.91,...,1.113089,0.688708,0,0.8,0.2,0,3,2.4,0.6,0.546481
2625,18/11/2018,2018,Parana,Palmeiras,1.0,1.0,D,17.68,6.97,1.15,...,0.530174,1.197132,1,0.0,0.4,1,1,0.4,1.8,0.539995
2653,02/12/2018,2018,Palmeiras,Vitoria,3.0,2.0,H,1.19,7.39,13.16,...,2.652401,0.450360,2,1.0,0.2,3,0,3.0,1.0,0.576121
2705,19/05/2019,2019,Internacional,CSA,2.0,0.0,H,1.22,6.05,17.04,...,2.021052,0.000000,2,0.8,0.0,3,0,2.4,0.5,0.585676
2860,26/09/2019,2019,Palmeiras,CSA,6.0,2.0,H,1.19,7.14,16.76,...,2.055755,0.303531,2,0.6,0.2,3,0,2.2,1.0,0.551834
2868,29/09/2019,2019,Santos,CSA,2.0,0.0,H,1.20,6.85,15.57,...,1.953423,0.611980,2,0.4,0.2,3,0,1.6,1.0,0.570150
2917,17/10/2019,2019,Palmeiras,Chapecoense-SC,1.0,0.0,H,1.16,7.49,21.35,...,2.186811,0.532754,2,0.8,0.0,3,0,2.6,0.4,0.509480
2933,27/10/2019,2019,Flamengo RJ,CSA,1.0,0.0,H,1.08,12.25,29.58,...,2.240401,0.517005,2,0.8,0.0,3,0,2.6,0.2,0.378048
2968,08/11/2019,2019,Gremio,CSA,2.0,1.0,H,1.15,8.06,20.64,...,2.037421,0.346094,2,0.6,0.0,3,0,2.0,0.0,0.497953
3011,01/12/2019,2019,Santos,Chapecoense-SC,2.0,0.0,H,1.22,6.28,14.46,...,2.347287,0.868921,2,0.8,0.4,3,0,2.6,1.6,0.598838
3023,05/12/2019,2019,Flamengo RJ,Avai,6.0,1.0,H,1.09,10.48,22.79,...,2.988702,0.224307,2,0.8,0.0,3,0,2.6,0.2,0.429599
3058,16/08/2020,2020,Palmeiras,Goias,1.0,1.0,D,1.18,7.15,16.75,...,2.151892,1.028096,1,0.4,0.2,1,1,1.4,0.8,0.549226
3356,26/01/2021,2020,Atletico-MG,Santos,2.0,0.0,H,1.21,6.78,15.14,...,2.116713,0.679987,2,0.6,0.2,3,0,2.0,0.6,0.577740
3523,11/07/2021,2021,Flamengo RJ,Chapecoense-SC,2.0,1.0,H,1.20,6.54,18.35,...,1.542435,1.243864,2,0.6,0.0,3,0,1.8,0.6,0.559050
3637,03/10/2021,2021,Flamengo RJ,Athletico-PR,3.0,0.0,H,1.21,7.16,13.33,...,1.523923,0.750327,2,0.6,0.0,3,0,1.8,0.0,0.584660
3795,10/12/2021,2021,Fluminense,Chapecoense-SC,3.0,0.0,H,1.19,6.94,16.79,...,1.403151,0.384840,2,1.0,0.0,3,0,3.0,0.2,0.556503
3860,21/05/2022,2022,Flamengo RJ,Goias,1.0,0.0,H,1.17,7.33,18.97,...,1.154607,1.357846,2,0.4,0.2,3,0,1.4,0.8,0.528323
3870,29/05/2022,2022,Atletico-MG,Avai,2.0,1.0,H,1.21,6.58,15.13,...,2.061136,0.381919,2,0.6,0.0,3,0,2.0,0.2,0.582922
4057,11/09/2022,2022,Palmeiras,Juventude,2.0,1.0,H,1.17,7.33,19.54,...,1.814172,0.439535,2,0.6,0.0,3,0,2.0,0.2,0.525074
4121,23/10/2022,2022,Palmeiras,Avai,3.0,0.0,H,1.16,8.19,21.00,...,1.728897,0.378536,2,0.6,0.0,3,0,2.2,0.4,0.495776
4136,27/10/2022,2022,Atletico-MG,Juventude,1.0,0.0,H,1.20,7.43,16.94,...,1.004177,0.478368,2,0.2,0.0,3,0,1.0,0.0,0.546179
4169,12/11/2022,2022,Flamengo RJ,Avai,1.0,2.0,A,1.17,8.17,16.16,...,1.908449,0.389146,0,0.6,0.0,0,3,2.0,0.2,0.528460
4535,30/11/2023,2023,Palmeiras,America MG,4.0,0.0,H,1.19,7.60,15.84,...,1.844047,1.296888,2,0.8,0.0,3,0,2.4,0.4,0.547963
4543,03/12/2023,2023,Bragantino,Coritiba,1.0,0.0,H,1.20,7.58,14.60,...,1.370973,1.735342,2,0.4,0.6,3,0,1.4,1.8,0.560979
4879,09/11/2024,2024,Botafogo RJ,Cuiaba,0.0,0.0,D,1.23,6.31,14.61,...,1.715592,0.324092,1,0.6,0.0,1,1,2.2,0.4,0.599148
4975,17/04/2025,2025,Flamengo RJ,Juventude,6.0,0.0,H,1.21,6.58,15.69,...,1.587514,1.282334,2,0.4,0.4,3,0,1.8,1.4,0.578519
5137,26/08/2025,2025,Flamengo RJ,Vitoria,8.0,0.0,H,1.20,6.84,16.98,...,1.953616,0.519859,2,1.0,0.0,3,0,3.0,0.6,0.560107
5256,03/12/2025,2025,Bahia,Sport Recife,2.0,0.0,H,1.20,7.37,13.52,...,1.662579,0.468147,2,1.0,0.0,3,0,3.0,0.2,0.575532

In [92]:
df_raw.columns

Index(['Date', 'Season', 'Home', 'Away', 'HG', 'AG', 'Res', 'PSCH', 'PSCD',
       'PSCA', 'Date_parsed', 'p_home', 'p_draw', 'p_away', 'dif_prob',
       'dif_draw', 'goal_diff', 'goal_total', 'bucket_favoritismo',
       'home_last5_goals', 'away_last5_goals', 'home_last5_concede',
       'away_last5_concede', 'home_ewma_5_goals', 'away_ewma_5_goals',
       'Res_num', 'home_last5_winrate', 'away_last5_winrate', 'home_points',
       'away_points', 'home_last5_ppg', 'away_last5_ppg', 'entropy'],
      dtype='str')

In [93]:
df_raw.to_csv("dados_processados.csv", index=False)